### Test Inregistrare Client
POST http://localhost:8082/api/auth/register
Content-Type: application/json

{
  "username": "ionut_student",
  "email": "ionut@test.com",
  "password": "parolaSecura123",
  "role": "CLIENT"
}